RiffMates/urls.py
from django.contrib import admin
from django.urls import path, include
from home import views as home_views
from django.conf import settings
from django.conf.urls.static import static
from ninja import NinjaAPI
from home.api import router as home_router
from promoters.api import router as promoters_router
from bands.api import router as bands_router

api = NinjaAPI(version="1.0")
api.add_router("/home/", home_router)
api.add_router("/promoters/", promoters_router)
api.add_router("/bands/", bands_router)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('credits/', home_views.credits),
    path('news/', home_views.news, name='news'),
    path('bands/', include("bands.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('content/', include('content.urls')),
    path("", home_views.home, name="home"),
    path("api/v1/", api.urls),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT)

bands/urls.py
# RiffMates/bands/urls.py
from django.urls import path
from bands import views
urlpatterns = [
    path('musician/<int:musician_id>/', views.musician, name="musician"),
    path('musicians/', views.musicians, name="musicians"),
    path('edit_musician/<int:musician_id>/', views.edit_musician, name="edit_musician"),
    path('add_musician/', views.edit_musician, name="add_musician"),
    path('bands/', views.bands, name="bands"),
    path('band/<int:band_id>/', views.band, name="band"),
    path('venues/', views.venues, name="venues"),
    path('add_venue/', views.edit_venue, name="add_venue"),
    path('edit_venue/<int:venue_id>', views.edit_venue, name="edit_venue"),
    path('restricted_page/', views.restricted_page, name="restricted_page"),
    path('musician_restricted/<int:musician_id>/', views.musician_restricted, name="musician_restricted"),
    path(
        "venues_restricted/", views.venues_restricted, name="venues_restricted"
    ),

]

bands/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth.signals import user_login_failed
from django.dispatch import receiver
from django.db.models.signals import post_save

# Create your models here.
class Musician(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    birth = models.DateField()
    description = models.TextField(blank=True)
    picture = models.ImageField(blank=True, null=True)

    class Meta:
        ordering = ["last_name", "first_name"]

    def __str__(self):
        return f"Musician(id={self.id}, last_name={self.last_name})"

class Venue(models.Model):
    name = models.CharField(max_length=20)
    description = models.TextField(blank=True)
    picture = models.ImageField(blank=True, null=True)
    class Meta:
        ordering = [
            "name",
        ]
    def __str__(self):
        return f"Venue(id={self.id}, name={self.name})"

class Room(models.Model):
    name = models.CharField(max_length=20)
    venue = models.ForeignKey(Venue, on_delete=models.CASCADE)
    class Meta:
        ordering = [
            "name",
        ]
    def __str__(self):
        return f"Room(id={self.id}, name={self.name})"

class Band(models.Model):
    name = models.CharField(max_length=20)
    musicians = models.ManyToManyField(Musician)
    class Meta:
        ordering = [
            "name",
        ]
    def __str__(self):
        return f"Band(id={self.id}, name={self.name})"

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    musician_profiles = models.ManyToManyField(Musician, blank=True)
    venues_controlled = models.ManyToManyField(Venue, blank=True)

@receiver(post_save, sender=User)
def user_post_save(sender, **kwargs):
    # Create UserProfile object if User object is new
    # and not loaded from fixture
    if kwargs["created"] and not kwargs["raw"]:
        user = kwargs["instance"]
        try:
            # Double check UserProfile doesn't exist already
            # (admin might create it before the signal fires)
            UserProfile.objects.get(user=user)
        except UserProfile.DoesNotExist:
            # No UserProfile exists for this user, create one
            UserProfile.objects.create(user=user)

@receiver(user_login_failed)
def track_login_failure(sender, **kwargs):
    username = kwargs["credentials"]["username"]
    url = kwargs["request"].path
    print(f"LOGIN Failure by {username} for {url}")

home/models.py
from django.db import models

# Create your models here.

bands/forms.py
# RiffMates/bands/forms.py
from django import forms
from bands.models import Venue
VenueForm = forms.modelform_factory(Venue,
                fields=["name", "description", "picture"])

MusicianForm = forms.modelform_factory(Venue,
                fields=["name", "description", "picture"])

bands/views.py
# RiffMates/bands/views.py
from datetime import date

from bands.forms import MusicianForm, VenueForm
from bands.models import Band, Musician, Venue
from django.contrib.auth.decorators import login_required, user_passes_test
from django.core.paginator import Paginator
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect, render


def musician(request, musician_id):
    musician = get_object_or_404(Musician, id=musician_id)
    musician.controller = False
    if request.user.is_staff:
        musician.controller = True
    elif hasattr(request.user, "userprofile"):
        # This view can be used by people who aren't logged in,
        # those users don't have a profile, need to validate
        # one exists before using it
        profile = request.user.userprofile
        musician.controller = profile.musician_profiles.filter(
            id=musician_id
        ).exists()

    data = {
        "musician": musician,
    }

    return render(request, "musician.html", data)


def edit_musician(request, musician_id=0):
    if musician_id != 0:
        musician = get_object_or_404(Musician, id=musician_id)
        if (
            not request.user.is_staff
            and not request.user.userprofile.musician_profiles.filter(
                id=musician_id
            ).exists()
        ):
            raise Http404("Can only edit controlled musicians")

    if request.method == "GET":
        if musician_id == 0:
            form = MusicianForm()
        else:
            form = MusicianForm(instance=musician)

    else:  # POST
        if musician_id == 0:
            musician = Musician.objects.create(birth=date(1900, 1, 1))

        form = MusicianForm(request.POST, request.FILES, instance=musician)

        if form.is_valid():
            musician = form.save()

            # Add the musician to the user's profile if this isn't staff
            if not request.user.is_staff:
                request.user.userprofile.musician_profiles.add(musician)

            return redirect("musicians")

    # Was a GET, or Form was not valid
    data = {
        "form": form,
    }

    return render(request, "edit_musician.html", data)


def _get_items_per_page(request):
    # Determine how many items to show per page, disallowing <1 or >50
    items_per_page = int(request.GET.get("items_per_page", 10))
    if items_per_page < 1:
        items_per_page = 10
    if items_per_page > 50:
        items_per_page = 50

    return items_per_page


def _get_page_num(request, paginator):
    # Get current page number for Pagination, using reasonable defaults
    page_num = int(request.GET.get("page", 1))

    if page_num < 1:
        page_num = 1
    elif page_num > paginator.num_pages:
        page_num = paginator.num_pages

    return page_num


def musicians(request):
    all_musicians = Musician.objects.all().order_by("last_name")
    items_per_page = _get_items_per_page(request)
    paginator = Paginator(all_musicians, items_per_page)
    page_num = _get_page_num(request, paginator)
    page = paginator.page(page_num)

    data = {
        "musicians": page.object_list,
        "page": page,
    }

    return render(request, "musicians.html", data)


def band(request, band_id):
    data = {
        "band": get_object_or_404(Band, id=band_id),
    }

    return render(request, "band.html", data)


def bands(request):
    all_bands = Band.objects.all().order_by("name")
    items_per_page = _get_items_per_page(request)
    paginator = Paginator(all_bands, items_per_page)

    page_num = _get_page_num(request, paginator)

    page = paginator.page(page_num)

    data = {
        "bands": page.object_list,
        "page": page,
    }

    return render(request, "bands.html", data)


def venues(request):
    all_venues = Venue.objects.all().order_by("name")
    profile = getattr(request.user, "userprofile", None)
    if profile:
        for venue in all_venues:
            # Mark the venue as "controlled" if the logged in user is
            # associated with the venue
            venue.controlled = profile.venues_controlled.filter(
                id=venue.id
            ).exists()
    else:
        # Anonymous user, can't be associated with the venue
        for venue in all_venues:
            venue.controlled = False

    items_per_page = _get_items_per_page(request)
    paginator = Paginator(all_venues, items_per_page)

    page_num = _get_page_num(request, paginator)

    page = paginator.page(page_num)

    data = {
        "venues": page.object_list,
        "page": page,
    }

    return render(request, "venues.html", data)


@login_required
def restricted_page(request):
    data = {
        "title": "Restricted Page",
        "content": "<h1>You are logged in</h1>",
    }

    return render(request, "general.html", data)


@login_required
def musician_restricted(request, musician_id):
    musician = get_object_or_404(Musician, id=musician_id)
    profile = request.user.userprofile
    allowed = False

    if profile.musician_profiles.filter(id=musician_id).exists():
        allowed = True
    else:
        # User is not this musician, check if they're a band-mate
        musician_profiles = set(profile.musician_profiles.all())
        for band in musician.band_set.all():
            band_musicians = set(band.musicians.all())
            if musician_profiles.intersection(band_musicians):
                allowed = True
                break

    if not allowed:
        raise Http404("Permission denied")

    content = f"""
        <h1>Musician Page: {musician.last_name}</h1>
    """
    data = {
        "title": "Musician Restricted",
        "content": content,
    }

    return render(request, "general.html", data)


def has_venue(user):
    try:
        return user.userprofile.venues_controlled.count() > 0
    except AttributeError:
        return False


@user_passes_test(has_venue)
def venues_restricted(request):
    return venues(request)


@login_required
def edit_venue(request, venue_id=0):
    if venue_id != 0:
        venue = get_object_or_404(Venue, id=venue_id)
        if not request.user.userprofile.venues_controlled.filter(
            id=venue_id
        ).exists():
            raise Http404("Can only edit controlled venues")

    if request.method == "GET":
        if venue_id == 0:
            form = VenueForm()
        else:
            form = VenueForm(instance=venue)

    else:  # POST
        if venue_id == 0:
            venue = Venue.objects.create()

        form = VenueForm(request.POST, request.FILES, instance=venue)

        if form.is_valid():
            venue = form.save()

            # Add the venue to the user's profile
            request.user.userprofile.venues_controlled.add(venue)
            return redirect("venues")

    # Was a GET, or Form was not valid
    data = {
        "form": form,
    }

    return render(request, "edit_venue.html", data)

home/views.py
from django.http import HttpResponse
from django.shortcuts import render

def credits(request):
    content = "Nicky\nYour Name"
    return HttpResponse(content, content_type="text/plain")

def news(request):
    data = {
        'news': [
            "RiffMates now has a news page!",
            "RiffMates has its first web page",
        ],
    }
    return render(request, "news2.html", data)

def home(request):

    return render(request, "home.html")

templates/band.html
<!-- RiffMates/templates/band.html -->
{% extends "base.html" %}
    {% block title %}
        {{block.super}}: Band Details
    {% endblock %}

    {% block content %}
    <h1>{{band.name}}</h1>

    <h2>Band Members</h2>
    <ul>
        {% for musician in band.musicians.all %}
        <li> <a href="{% url 'musician' musician.id %}">
            {{musician.last_name}}, {{musician.first_name}}
        </a> </li>
        {% empty %}
            <li> <i>No members</i> </li>
        {% endfor %}
    </ul>
{% endblock content %}

templates/bands.html
<!-- RiffMates/templates/bands.html -->
{% extends "base.html" %}
    {% block title %}
    {{block.super}}: Band Listing
    {% endblock %}
    {% block content %}
    <h1>Bands</h1>
    <ul>
        {% for band in bands %}
            <li> <a href="{% url 'band' band.id %}"> {{band.name}} </a> </li>
                {% empty %}
            <li> <i>No bands in the database</i> </li>
        {% endfor %}
    </ul>
    {% if page.has_other_pages %}
        {% if page.has_previous %}
            <a href="{% url 'bands' %}?page={{page.previous_page_number}}"
            > Prev</a>
            &nbsp;&nbsp;&nbsp;
        {% endif %}
        {% if page.has_next %}
            <a href="{% url 'bands' %}?page={{page.next_page_number}}"> Next</a>
        {% endif %}
    {% endif %}
{% endblock content %}

templates/base.html
<!-- RiffMates/templates/base.html -->
<!doctype html>
<html lang="en">
<head>
    <title>
        {% block title %}RiffMates{% endblock %}
    </title>
</head>
<body>
    <div style="float: right;">
        <a href="{% url 'home' %}">Home</a> &nbsp;&nbsp;
        {% if user.is_authenticated %}
        Hello, {{user.username}}! &nbsp;

        <form id="logout-form" method="post"
                action="{% url 'logout' %}"
                style="display: inline;">
            {% csrf_token %}
            <button type="submit"
                style="background: none; border: none; cursor: pointer; padding: 0; text-decoration: underline;"
                >Logout</button>
        </form>
        {% else %}
            <a href="{% url 'login' %}">Login</a>
        {% endif %}
    </div>

        {% block content %}
        {% endblock content %}
</body>
</html>

templates/comment.html
<!-- RiffMates/templates/comment.html -->
{% extends "base.html" %}
    {% block content %}
    <h1>Comment</h1>
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button class="btn btn-dark" type="submit">Send</button>
    </form>
{% endblock content %}

templates/edit_musician.html
<!-- RiffMates/templates/edit_venue.html -->
{% extends "base.html" %}

{% block content %}
<h1>Musicion Details</h1>

<form enctype="multipart/form-data" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <button class="btn btn-dark" type="submit">Save</button>
</form>
{% endblock content %}

templates/edit_venue.html
<!-- RiffMates/templates/edit_venue.html -->
{% extends "base.html" %}

{% block content %}
<h1>Venue Details</h1>

<form enctype="multipart/form-data" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <button class="btn btn-dark" type="submit">Save</button>
</form>
{% endblock content %}

templates/home.html
<!-- RiffMates/templates/home.html -->
{% extends "base.html" %}
{% load static %}

{% block content %}
    <img src="{% static 'img/logo.png' %}" height="100">
    <h1>Welcome to RiffMates!</h1>

    <ul>
        <li> <a href="{% url 'news' %}">News</a> </li>
        <li> <a href="{% url 'musicians' %}">Musicians</a> </li>
        <li> <a href="{% url 'bands' %}">Bands</a> </li>
        <li> <a href="{% url 'venues' %}">Venues</a> </li>
        <li> <a href="{% url 'list_ads' %}">Classified Ads</a> </li>
        <li> <a href="{% url 'comment' %}">Leave a comment</a> </li>
        <li> <a href="{% url 'add_musician' %}">Add Musician Profile</a> </li>
    </ul>
{% endblock content %}

templates/list_ads.html
<!-- RiffMates/templates/list_ads.html -->
{% extends "base.html" %}

{% block content %}
    <h1>Musicians Seeking Bands </h1>
    {% for ad in seeking_band %}
        {% if ad.owner == request.user or request.user.is_staff %}
            <a href="{% url 'edit_seeking_ad' ad.id %}">Edit</a>
        {% endif %}

        <p>
            {{ad.date}} &mdash;
            {{ad.musician.first_name}} {{ad.musician.last_name}}
            <br/>
            <i>{{ad.content}}</i>
        </p>
        {% empty %}
        <p> <i>No ads at this time</i> </p>
    {% endfor %}

    <h1>Bands Seeking Musicians </h1>
    {% for ad in seeking_musician %}
        {% if ad.owner == request.user or request.user.is_staff %}
            <a href="{% url 'edit_seeking_ad' ad.id %}">Edit</a>
        {% endif %}

        <p>
            {{ad.date}} &mdash; {{ad.band.name}}
            <br/>
            <i>{{ad.content}}</i>
         </p>
    {% empty %}
        <p> <i>No ads at this time</i> </p>
    {% endfor %}


{% endblock content %}

templates/musician.html
<!-- RiffMates/templates/musician.html -->
{% extends "base.html" %}
{% block title %}
    {{block.super}}: Musician Details
{% endblock %}

{% block content %}
    <h1>{{musician.first_name}} {{musician.last_name}}</h1>
    {% if musician.controller %}
        <a href="{% url 'edit_musician' musician.id %}">Edit</a>
    {% endif %}

    {% if musician.picture %}
        <p>
        <img src="{{musician.picture.url}}"/>
        </p>
    {% endif %}

    {% if musician.description %}
        <p> {{musician.description}} </p>
    {% endif %}
    <p> Was born {{musician.birth}}. </p>
{% endblock content %}

templates/musicians.html
<!-- RiffMates/templates/musicians.html -->
{% extends "base.html" %}

{% block title %}
    {{block.super}}: Musician Listing
{% endblock %}

{% block content %}
    <h1>Musicians</h1>
    <ul>
        {% for musician in musicians %}
            <li> <a href="{% url 'musician' musician.id %}">
                {{musician.last_name}}, {{musician.first_name}}
            </a> </li>
            {% empty %}
            <li> <i>No musicians in the database</i> </li>
        {% endfor %}
    </ul>
{% endblock content %}

{% if page.has_other_pages %}
    {% if page.has_previous %}
        <a href="{% url 'musicians' %}?page={{page.previous_page_number}}"
        >Prev</a> &nbsp;&nbsp;&nbsp;
    {% endif %}
    {% if page.has_next %}
        <a href="{% url 'musicians' %}?page={{page.next_page_number}}"
        >Next</a>
    {% endif %}
{% endif %}

templates/news.html
<!-- RiffMates/templates/news.html -->
<!doctype html>
<html lang="en">
<head>
    <title>RiffMates News</title>
</head>
<body>
    <h1>RiffMates News</h1>
    <ul>
        {% for item in news %}
            <li>{{ item }}</li>
        {% endfor %}
    </ul>
</body>
</html>

templates/news2.html
<!-- RiffMates/templates/news2.html -->
{% extends "base.html" %}

{% block title %}
    {{block.super}}: News
{% endblock %}
{% block content %}
    <h1>RiffMates News (2)</h1>
    <ul>
        {% for item in news %}
        <li>{{ item }}</li>
        {% endfor %}
    </ul>
{% endblock content %}

templates/seeking_ad.html
<!-- RiffMates/templates/seeking_ad.html -->
{% extends "base.html" %}
{% block content %}
    <h1>Seeking Ad</h1>

    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button class="btn btn-dark" type="submit">Save</button>
    </form>

{% endblock content %}

templates/venues.html
<!-- RiffMates/templates/venues.html -->
{% extends "base.html" %}
{% block title %}
{{block.super}}: Venue Listing
{% endblock %}
{% block content %}
    <h1>Venues</h1>
    {% if user.is_authenticated %}
        <a href="{% url 'add_venue' %}">Add Venue</a>
    {% endif %}

    <ul>
        {% for venue in venues %}
            <b> {{venue.name}} </b>
            {% if venue.controlled %}
            <br/>
                &nbsp; &nbsp; &nbsp;
                <a href="{% url 'edit_venue' venue.id %}"
                >Edit</a>
                <br/>
            {% endif %}
            {% if venue.picture %}
                <br/>
                &nbsp; &nbsp; &nbsp;
                <img src="{{venue.picture.url}}" height="50"/>
                <br/>
            {% endif %}
            {% if venue.description %}
                <br/>
                <i> &nbsp; &nbsp; &nbsp; {{venue.description }} </i>
                <br/>
            {% endif %}
            Rooms:
            <ul>
                {% for room in venue.room_set.all %}
                    <li> {{room.name}} </li>
                    {% empty %}
                    <li> <i>No rooms for this venue</i> </li>
                {% endfor %}
            </ul>
            {% empty %}
            <li> <i>No venues in the database</i> </li>
        {% endfor %}
    </ul>
    {% if page.has_other_pages %}
        {% if page.has_previous %}
            <a href="{% url 'venues' %}?page={{page.previous_page_number}}"> Prev</a>&nbsp;&nbsp;&nbsp;
        {% endif %}
        {% if page.has_next %}
            <a href="{% url 'venues' %}?page={{page.next_page_number}}"> Next</a>
        {% endif %}
    {% endif %}
{% endblock content %}